// manual/vue/src/components/AsyncTest.vue
<template>
  <div class="test-case">
    <h3>⚡ Async Function Test</h3>
    <p>Test debouncing with async functions (simulates API call).</p>

    <div class="test-controls">
      <label>
        Input:
        <input
          type="text"
          v-model="input"
          @input="handleInputChange"
          placeholder="Type to trigger async operation..."
        />
      </label>
      <span v-if="loading" class="loading">Loading...</span>
    </div>

    <div class="test-output">
      <p><strong>Result:</strong> {{ result }}</p>
    </div>

    <div class="test-logs">
      <h4>Logs:</h4>
      <div class="logs-container">
        <div v-for="(log, index) in logs" :key="index" class="log-entry">{{ log }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useDebounce } from 'use-simple-debounce/vue'

const input = ref('')
const result = ref('')
const loading = ref(false)
const logs = ref<string[]>([])

const addLog = (message: string) => {
  logs.value.push(`${new Date().toLocaleTimeString()}: ${message}`)
}

const debouncedAsyncOperation = useDebounce(500)

const handleInputChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  const value = target.value
  input.value = value
  addLog(`Input changed: "${value}"`)
  debouncedAsyncOperation(async () => {
    loading.value = true
    addLog(`Starting async operation for: "${value}"`)

    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 1000))

    const processed = value.toUpperCase()
    result.value = processed
    loading.value = false
    addLog(`Async operation completed: "${processed}"`)
  })
}
</script>

// manual/svelte/src/components/AsyncTest.svelte
<script lang="ts">
  import { debounce } from 'use-simple-debounce/svelte'

  let input = ''
  let result = ''
  let loading = false
  let logs: string[] = []

  function addLog(message: string) {
    logs = [...logs, `${new Date().toLocaleTimeString()}: ${message}`]
  }

  const debouncedAsyncOperation = debounce(async () => {
    loading = true
    addLog(`Starting async operation for: "${input}"`)

    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 1000))

    result = input.toUpperCase()
    loading = false
    addLog(`Async operation completed: "${result}"`)
  }, 500)

  function handleInputChange(event: Event) {
    const target = event.target as HTMLInputElement
    input = target.value
    addLog(`Input changed: "${input}"`)
    debouncedAsyncOperation()
  }
</script>

<div class="test-case">
  <h3>⚡ Async Function Test</h3>
  <p>Test debouncing with async functions (simulates API call).</p>

  <div class="test-controls">
    <label>
      Input:
      <input
        type="text"
        bind:value={input}
        on:input={handleInputChange}
        placeholder="Type to trigger async operation..."
      />
    </label>
  </div>

  <div class="test-output">
    <p><strong>Result:</strong> {result}</p>
    <p><strong>Loading:</strong> {loading ? 'Yes' : 'No'}</p>
  </div>

  <div class="test-logs">
    <h4>Logs:</h4>
    <div class="logs-container">
      {#each logs as log}
        <div class="log-entry">{log}</div>
      {/each}
    </div>
  </div>
</div>
