// manual/vue/src/App.vue
<template>
  <div class="app">
    <nav class="sidebar">
      <h2>Test Cases</h2>
      <ul>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'basic' }]"
            @click="setActiveTest('basic')"
          >
            Basic Debounce
          </button>
        </li>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'rapid' }]"
            @click="setActiveTest('rapid')"
          >
            Rapid Calls
          </button>
        </li>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'async' }]"
            @click="setActiveTest('async')"
          >
            Async Functions
          </button>
        </li>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'delay' }]"
            @click="setActiveTest('delay')"
          >
            Custom Delay
          </button>
        </li>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'api' }]"
            @click="setActiveTest('api')"
          >
            API Simulation
          </button>
        </li>
        <li>
          <button
            :class="['test-button', { active: activeTest === 'cleanup' }]"
            @click="setActiveTest('cleanup')"
          >
            Cleanup Test
          </button>
        </li>
      </ul>
    </nav>

    <main class="main-content">
      <header class="page-header">
        <h1>use-simple-debounce Vue Manual Tests</h1>
        <p><img src="/src/assets/vue-logo.svg" alt="Vue" class="framework-logo" /> Vue Implementation</p>
      </header>
      <component :is="currentComponent" />
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import BasicTest from './components/BasicTest.vue'
import RapidCallsTest from './components/RapidCallsTest.vue'
import AsyncTest from './components/AsyncTest.vue'
import DelayTest from './components/DelayTest.vue'
import APITest from './components/APITest.vue'
import CleanupTest from './components/CleanupTest.vue'

type TestCase = 'basic' | 'rapid' | 'async' | 'delay' | 'api' | 'cleanup'

const activeTest = ref<TestCase>('basic')

const setActiveTest = (test: TestCase) => {
  activeTest.value = test
}

const currentComponent = computed(() => {
  switch (activeTest.value) {
    case 'basic':
      return BasicTest
    case 'rapid':
      return RapidCallsTest
    case 'async':
      return AsyncTest
    case 'delay':
      return DelayTest
    case 'api':
      return APITest
    case 'cleanup':
      return CleanupTest
    default:
      return BasicTest
  }
})
</script>

<style>
@import './index.css';
</style>

// manual/react/src/App.tsx
import React, { useState } from 'react';
import './App.css';
import { BasicTest } from './components/BasicTest';
import { RapidCallsTest } from './components/RapidCallsTest';
import { AsyncTest } from './components/AsyncTest';
import { DelayTest } from './components/DelayTest';
import { APITest } from './components/APITest';
import { CleanupTest } from './components/CleanupTest';

type TestCase = 'basic' | 'rapid' | 'async' | 'delay' | 'api' | 'cleanup';

const App: React.FC = () => {
  const [activeTest, setActiveTest] = useState<TestCase>('basic');

  const renderTestCase = () => {
    switch (activeTest) {
      case 'basic':
        return <BasicTest />;
      case 'rapid':
        return <RapidCallsTest />;
      case 'async':
        return <AsyncTest />;
      case 'delay':
        return <DelayTest />;
      case 'api':
        return <APITest />;
      case 'cleanup':
        return <CleanupTest />;
      default:
        return <BasicTest />;
    }
  };

  return (
    <div className="app">
      <nav className="sidebar">
        <h2>Test Cases</h2>
        <ul>
          <li>
            <button
              className={`test-button ${activeTest === 'basic' ? 'active' : ''}`}
              onClick={() => setActiveTest('basic')}
            >
              Basic Debounce
            </button>
          </li>
          <li>
            <button
              className={`test-button ${activeTest === 'rapid' ? 'active' : ''}`}
              onClick={() => setActiveTest('rapid')}
            >
              Rapid Calls
            </button>
          </li>
          <li>
            <button
              className={`test-button ${activeTest === 'async' ? 'active' : ''}`}
              onClick={() => setActiveTest('async')}
            >
              Async Functions
            </button>
          </li>
          <li>
            <button
              className={`test-button ${activeTest === 'delay' ? 'active' : ''}`}
              onClick={() => setActiveTest('delay')}
            >
              Custom Delay
            </button>
          </li>
          <li>
            <button
              className={`test-button ${activeTest === 'api' ? 'active' : ''}`}
              onClick={() => setActiveTest('api')}
            >
              API Simulation
            </button>
          </li>
          <li>
            <button
              className={`test-button ${activeTest === 'cleanup' ? 'active' : ''}`}
              onClick={() => setActiveTest('cleanup')}
            >
              Cleanup Test
            </button>
          </li>
        </ul>
      </nav>

      <main className="main-content">
        <header className="page-header">
          <h1>use-simple-debounce React Manual Tests</h1>
          <p>
            <img src="/src/assets/react-logo.svg" alt="React" className="framework-logo" /> React
            Implementation
          </p>
        </header>
        {renderTestCase()}
      </main>
    </div>
  );
};

export default App;
