// manual/preact/src/components/CleanupTest.tsx
import { useState } from 'preact/hooks';
import { DebounceComponent } from './DebounceComponent';

export function CleanupTest() {
  const [componentMounted, setComponentMounted] = useState(true);
  const [logs, setLogs] = useState<string[]>([]);

  const addLog = (message: string) => {
    setLogs(prev => [...prev, `${new Date().toLocaleTimeString()}: ${message}`]);
  };

  const mountComponent = () => {
    setComponentMounted(true);
    addLog('Mounting DebounceComponent');
  };

  const unmountComponent = () => {
    setComponentMounted(false);
    addLog('Unmounting DebounceComponent');
  };

  const clearLogs = () => {
    setLogs([]);
  };

  return (
    <div className="test-case">
      <h3>⚡ Cleanup Test</h3>
      <p>Test that debounced functions are properly cleaned up when components unmount.</p>
      <p><em>Type in the input, then unmount the component before the 5s delay expires.</em></p>
      <p><em>The debounced function is called with console.log after 5 seconds.</em></p>

      <div className="test-controls">
        <button onClick={mountComponent} disabled={componentMounted}>
          {componentMounted ? 'Component Mounted' : 'Mount Component'}
        </button>
        <button onClick={unmountComponent} disabled={!componentMounted}>
          {!componentMounted ? 'Component Unmounted' : 'Unmount Component'}
        </button>
        <button onClick={clearLogs}>Clear Logs</button>
      </div>

      <div className="component-container">
        {componentMounted && <DebounceComponent addLog={addLog} />}
      </div>

      <div className="test-logs">
        <h4>Logs:</h4>
        <div className="logs-container">
          {logs.map((log, index) => (
            <div key={index} className="log-entry">{log}</div>
          ))}
        </div>
      </div>
    </div>
  );
}

// manual/svelte5/src/components/CleanupTest.svelte
<script lang="ts">
  import DebounceComponent from './DebounceComponent.svelte'

  let componentMounted = $state(true)
  let logs = $state<string[]>([])

  function addLog(message: string) {
    logs = [...logs, `${new Date().toLocaleTimeString()}: ${message}`]
  }

  function mountComponent() {
    componentMounted = true
    addLog('Mounting DebounceComponent')
  }

  function unmountComponent() {
    componentMounted = false
    addLog('Unmounting DebounceComponent')
  }

  function clearLogs() {
    logs = []
  }
</script>

<div class="test-case">
  <h3>⚡ Cleanup Test</h3>
  <p>Test that debounced functions are properly cleaned up when components unmount.</p>
  <p><em>Type in the input, then unmount the component before the 5s delay expires.</em></p>
  <p><em>The debounced function is called with console.log after 5 seconds.</em></p>

  <div class="test-controls">
    <button onclick={mountComponent} disabled={componentMounted}>
      {componentMounted ? 'Component Mounted' : 'Mount Component'}
    </button>
    <button onclick={unmountComponent} disabled={!componentMounted}>
      {!componentMounted ? 'Component Unmounted' : 'Unmount Component'}
    </button>
    <button onclick={clearLogs}>Clear Logs</button>
  </div>

  <div class="component-container">
    {#if componentMounted}
      <DebounceComponent {addLog} />
    {/if}
  </div>

  <div class="test-logs">
    <h4>Logs:</h4>
    <div class="logs-container">
      {#each logs as log}
        <div class="log-entry">{log}</div>
      {/each}
    </div>
  </div>
</div>
