// manual/svelte5/src/components/RapidCallsTest.svelte
<script lang="ts">
	import { createDebounce } from 'use-simple-debounce/svelte';

	let count = $state(0);
	let debouncedCount = $state(0);
	let logs = $state<string[]>([]);
	let debouncedCountRef = $state(0);

	function addLog(message: string) {
		logs = [...logs, `${new Date().toLocaleTimeString()}: ${message}`];
	}

	const debounced = createDebounce();

	function handleRapidCalls() {
		for (let i = 0; i < 10; i++) {
			setTimeout(() => {
				count += 1;
				addLog(`Immediate count: ${count}`);
				debounced(() => {
					debouncedCountRef = debouncedCountRef + 1;
					debouncedCount = debouncedCountRef;
					addLog(`Debounced count: ${count}`);
				}, 300);
			}, i * 50); // Call every 50ms
		}
	}

	function reset() {
		count = 0;
		debouncedCount = 0;
		debouncedCountRef = 0;
		logs = [];
	}
</script>

<div class="test-case">
	<h3>⚡ Rapid Calls Test</h3>
	<p>Test debouncing with rapid successive calls (10 calls in 500ms).</p>

	<div class="test-controls">
		<button onclick={handleRapidCalls}>Trigger Rapid Calls</button>
		<button onclick={reset}>Reset</button>
	</div>

	<div class="test-output">
		<p><strong>Immediate Count:</strong> {count}</p>
		<p><strong>Debounced Count:</strong> {debouncedCount}</p>
	</div>

	<div class="test-logs">
		<h4>Logs:</h4>
		<div class="logs-container">
			{#each logs as log}
				<div class="log-entry">{log}</div>
			{/each}
		</div>
	</div>
</div>

// manual/vue/src/components/RapidCallsTest.vue
<template>
  <div class="test-case">
    <h3>⚡ Rapid Calls Test</h3>
    <p>Test debouncing with rapid successive calls (10 calls in 500ms).</p>

    <div class="test-controls">
      <button @click="handleRapidCalls">Trigger Rapid Calls</button>
      <button @click="reset">Reset</button>
    </div>

    <div class="test-output">
      <p><strong>Immediate Count:</strong> {{ count }}</p>
      <p><strong>Debounced Count:</strong> {{ debouncedCount }}</p>
    </div>

    <div class="test-logs">
      <h4>Logs:</h4>
      <div class="logs-container">
        <div v-for="(log, index) in logs" :key="index" class="log-entry">{{ log }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useDebounce } from 'use-simple-debounce/vue'

const count = ref(0)
const debouncedCount = ref(0)
const logs = ref<string[]>([])
const debouncedCountRef = ref(0)

const addLog = (message: string) => {
  logs.value.push(`${new Date().toLocaleTimeString()}: ${message}`)
}

const debounced = useDebounce()

const handleRapidCalls = () => {
  for (let i = 0; i < 10; i++) {
    setTimeout(() => {
      count.value += 1
      addLog(`Immediate count: ${count.value}`)
      debounced(() => {
        debouncedCountRef.value = debouncedCountRef.value + 1
        debouncedCount.value = debouncedCountRef.value
        addLog(`Debounced count: ${count.value}`)
      }, 300)
    }, i * 50) // Call every 50ms
  }
}

const reset = () => {
  count.value = 0
  debouncedCount.value = 0
  debouncedCountRef.value = 0
  logs.value = []
}
</script>
