// manual/svelte/src/components/RapidCallsTest.svelte
<script lang="ts">
  import { debounce } from 'use-simple-debounce/svelte'

  let count = 0
  let debouncedCount = 0
  let logs: string[] = []

  function addLog(message: string) {
    logs = [...logs, `${new Date().toLocaleTimeString()}: ${message}`]
  }

  const debouncedUpdate = debounce((newCount: number) => {
    debouncedCount = newCount
    addLog(`Debounced count: ${newCount}`)
  }, 300)

  function handleRapidCalls() {
    for (let i = 0; i < 10; i++) {
      setTimeout(() => {
        count += 1
        addLog(`Immediate count: ${count}`)
        debouncedUpdate(count)
      }, i * 50) // Call every 50ms
    }
  }

  function reset() {
    count = 0
    debouncedCount = 0
    logs = []
  }
</script>

<div class="test-case">
  <h3>⚡ Rapid Calls Test</h3>
  <p>Test debouncing with rapid successive calls (10 calls in 500ms).</p>

  <div class="test-controls">
    <button on:click={handleRapidCalls}>Trigger Rapid Calls</button>
    <button on:click={reset}>Reset</button>
  </div>

  <div class="test-output">
    <p><strong>Immediate Count:</strong> {count}</p>
    <p><strong>Debounced Count:</strong> {debouncedCount}</p>
  </div>

  <div class="test-logs">
    <h4>Logs:</h4>
    <div class="logs-container">
      {#each logs as log}
        <div class="log-entry">{log}</div>
      {/each}
    </div>
  </div>
</div>

// manual/vue/src/components/RapidCallsTest.vue
<template>
  <div class="test-case">
    <h3>⚡ Rapid Calls Test</h3>
    <p>Test debouncing with rapid successive calls (10 calls in 500ms).</p>

    <div class="test-controls">
      <button @click="handleRapidCalls">Trigger Rapid Calls</button>
      <button @click="reset">Reset</button>
    </div>

    <div class="test-output">
      <p><strong>Immediate Count:</strong> {{ count }}</p>
      <p><strong>Debounced Count:</strong> {{ debouncedCount }}</p>
    </div>

    <div class="test-logs">
      <h4>Logs:</h4>
      <div class="logs-container">
        <div v-for="(log, index) in logs" :key="index" class="log-entry">{{ log }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useDebounce } from 'use-simple-debounce/vue'

const count = ref(0)
const debouncedCount = ref(0)
const logs = ref<string[]>([])

const addLog = (message: string) => {
  logs.value.push(`${new Date().toLocaleTimeString()}: ${message}`)
}

const debouncedUpdate = useDebounce(300)

const handleRapidCalls = () => {
  for (let i = 0; i < 10; i++) {
    setTimeout(() => {
      count.value += 1
      addLog(`Immediate count: ${count.value}`)
      debouncedUpdate(() => {
        debouncedCount.value = count.value
        addLog(`Debounced count: ${count.value}`)
      })
    }, i * 50) // Call every 50ms
  }
}

const reset = () => {
  count.value = 0
  debouncedCount.value = 0
  logs.value = []
}
</script>
